/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automaton.testdomain.tables;


import de.quinscape.automaton.testdomain.Indexes;
import de.quinscape.automaton.testdomain.Keys;
import de.quinscape.automaton.testdomain.Public;
import de.quinscape.automaton.testdomain.tables.records.BazLinkRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BazLink extends TableImpl<BazLinkRecord> {

    private static final long serialVersionUID = 65843887;

    /**
     * The reference instance of <code>public.baz_link</code>
     */
    public static final BazLink BAZ_LINK = new BazLink();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BazLinkRecord> getRecordType() {
        return BazLinkRecord.class;
    }

    /**
     * The column <code>public.baz_link.id</code>.
     */
    public final TableField<BazLinkRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.baz_link.baz_id</code>.
     */
    public final TableField<BazLinkRecord, String> BAZ_ID = createField("baz_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * The column <code>public.baz_link.value_id</code>.
     */
    public final TableField<BazLinkRecord, String> VALUE_ID = createField("value_id", org.jooq.impl.SQLDataType.VARCHAR(36).nullable(false), this, "");

    /**
     * Create a <code>public.baz_link</code> table reference
     */
    public BazLink() {
        this(DSL.name("baz_link"), null);
    }

    /**
     * Create an aliased <code>public.baz_link</code> table reference
     */
    public BazLink(String alias) {
        this(DSL.name(alias), BAZ_LINK);
    }

    /**
     * Create an aliased <code>public.baz_link</code> table reference
     */
    public BazLink(Name alias) {
        this(alias, BAZ_LINK);
    }

    private BazLink(Name alias, Table<BazLinkRecord> aliased) {
        this(alias, aliased, null);
    }

    private BazLink(Name alias, Table<BazLinkRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.BAZ_LINK_BAZ_ID_VALUE_ID_KEY, Indexes.PK_BAZ_LINK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<BazLinkRecord> getPrimaryKey() {
        return Keys.PK_BAZ_LINK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<BazLinkRecord>> getKeys() {
        return Arrays.<UniqueKey<BazLinkRecord>>asList(Keys.PK_BAZ_LINK, Keys.BAZ_LINK_BAZ_ID_VALUE_ID_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<BazLinkRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<BazLinkRecord, ?>>asList(Keys.BAZ_LINK__FK_BAZ_LINK_BAZ_ID, Keys.BAZ_LINK__FK_BAZ_LINK_VALUE_ID);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BazLink as(String alias) {
        return new BazLink(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BazLink as(Name alias) {
        return new BazLink(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public BazLink rename(String name) {
        return new BazLink(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BazLink rename(Name name) {
        return new BazLink(name, null);
    }
}
