/*
 * This file is generated by jOOQ.
*/
package de.quinscape.automaton.testdomain.tables;


import de.quinscape.automaton.testdomain.Indexes;
import de.quinscape.automaton.testdomain.Keys;
import de.quinscape.automaton.testdomain.Public;
import de.quinscape.automaton.testdomain.tables.records.FooTypeRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.6"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FooType extends TableImpl<FooTypeRecord> {

    private static final long serialVersionUID = -1050412430;

    /**
     * The reference instance of <code>public.foo_type</code>
     */
    public static final FooType FOO_TYPE = new FooType();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<FooTypeRecord> getRecordType() {
        return FooTypeRecord.class;
    }

    /**
     * The column <code>public.foo_type.ordinal</code>.
     */
    public final TableField<FooTypeRecord, Integer> ORDINAL = createField("ordinal", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.foo_type.name</code>.
     */
    public final TableField<FooTypeRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * Create a <code>public.foo_type</code> table reference
     */
    public FooType() {
        this(DSL.name("foo_type"), null);
    }

    /**
     * Create an aliased <code>public.foo_type</code> table reference
     */
    public FooType(String alias) {
        this(DSL.name(alias), FOO_TYPE);
    }

    /**
     * Create an aliased <code>public.foo_type</code> table reference
     */
    public FooType(Name alias) {
        this(alias, FOO_TYPE);
    }

    private FooType(Name alias, Table<FooTypeRecord> aliased) {
        this(alias, aliased, null);
    }

    private FooType(Name alias, Table<FooTypeRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.FOO_TYPE_NAME_KEY, Indexes.PK_FOO_TYPE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<FooTypeRecord> getPrimaryKey() {
        return Keys.PK_FOO_TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<FooTypeRecord>> getKeys() {
        return Arrays.<UniqueKey<FooTypeRecord>>asList(Keys.PK_FOO_TYPE, Keys.FOO_TYPE_NAME_KEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FooType as(String alias) {
        return new FooType(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public FooType as(Name alias) {
        return new FooType(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public FooType rename(String name) {
        return new FooType(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public FooType rename(Name name) {
        return new FooType(name, null);
    }
}
